/**
 * This is an autogenerated file created by the Stencil build process.
 * It contains typing information for all components that exist in this project
 * and imports for stencil collections that might be configured in your stencil.config.js file
 */

import '@stencil/core';

declare global {
  namespace JSX {
    interface Element {}
    export interface IntrinsicElements {}
  }
  namespace JSXElements {}

  interface HTMLStencilElement extends HTMLElement {
    componentOnReady(): Promise<this>;
    componentOnReady(done: (ele?: this) => void): void;

    forceUpdate(): void;
  }

  interface HTMLAttributes {}
}


declare global {
  interface HTMLAuButtonElement extends HTMLStencilElement {

  }
  var HTMLAuButtonElement: {
    prototype: HTMLAuButtonElement;
    new (): HTMLAuButtonElement;
  };
  interface HTMLElementTagNameMap {
    'au-button': HTMLAuButtonElement;
  }
  interface ElementTagNameMap {
    'au-button': HTMLAuButtonElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'au-button': JSXElements.AuButtonAttributes;
    }
  }
  namespace JSXElements {
    export interface AuButtonAttributes extends HTMLAttributes {

    }
  }
}

declare global { namespace JSX { interface StencilJSX {} } }
